
maxMapNumber = 10;

VmCaLinkedMap = cell(3,3);

VmCaLinkedMap{1,1} = 'Act Linked';
VmCaLinkedMap{2,1} = 'Rep Linked';
VmCaLinkedMap{3,1} = 'Duration Linked';


% act
actLinkedMapDataTitle = { '(1) Win Start Index', '(2) Win End Index', ...
    '(3) Area Mode', '(4) AP Mode', ...
    '(5) LB', '(6) UB', ...
    '(7) Data Section Time', ...
    '(8) Data Section Camera 1', '(9) Data Section Camera 2'...
    '(10) Locs Act Camera 1', '(11) Locs Act Camera 2', ...
    '(12) Act Delta (Camera 1 Minus Camera 2) Matrix', ...
    '(13) Ensemble Peaks Number', ...
    '(14) Map User Comment'};
parameterNumber = length( actLinkedMapDataTitle );
actLinkedMapData = cell(1, parameterNumber, maxMapNumber);
VmCaLinkedMap{1,2} = actLinkedMapDataTitle;
VmCaLinkedMap{1,3} = actLinkedMapData;

clear actLinkedMapDataTitle actLinkedMapData

% rep
repLinkedMapDataTitle = { '(1) Win Start Index', '(2) Win End Index', ...
    '(3) Area Mode', '(4) AP Mode', ...
    '(5) Rep Level', ...
    '(6) LB', '(7) UB', ...
    '(8) Data Section Time', ...
    '(9) Data Section Camera 1', '(10) Data Section Camera 2'...
    '(11) Locs Rep Camera 1', '(12) Locs Rep Camera 2' ...
    '(13) Rep Delta (Camera 1 Minus Camera 2) Matrix', ...
    '(14) Ensemble Peaks Number', ...
    '(15) Map User Comment'};
parameterNumber = length( repLinkedMapDataTitle );
repLinkedMapData = cell(1, parameterNumber, maxMapNumber);
VmCaLinkedMap{2,2} = repLinkedMapDataTitle;
VmCaLinkedMap{2,3} = repLinkedMapData;
clear repLinkedMapDataTitle repLinkedMapData

% duration
durationLinkedMapDataTitle = { '(1) Win Start Index', '(2) Win End Index', ...
    '(3) Area Mode', '(4) AP Mode', ...
    '(5) Duration Level', ...
    '(6) LB', '(7) UB', ...
    '(8) Data Section Time', ...
    '(9) Data Section Camera 1', '(10) Data Section Camera 2' ...
    '(11) Locs Act Camera 1', '(12) Locs Act Camera 2', ...
    '(13) Locs Rep Camera 1', '(14) Locs Rep Camera 2' ...
    '(15) Duration Delta (Camera 1 Minus Camera 2) Matrix', ...
    '(16) Ensemble Peaks Number', ...
    '(17) Map User Comment'};
parameterNumber = length( durationLinkedMapDataTitle );
durationLinkedMapData = cell(1, parameterNumber, maxMapNumber);
VmCaLinkedMap{3,2} = durationLinkedMapDataTitle;
VmCaLinkedMap{3,3} = durationLinkedMapData;
clear durationMapDataTitle durationMapData


VmCaLinkedMeasurement = { 'Camera 1 minus Camera 2', VmCaLinkedMap };
